#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Unstaging .env files"
git rm --cached */.env --ignore-unmatch

echo "Running ESLint..."
cd client && npx eslint *.js --fix
cd ../server && npx eslint *.js --fix
cd ..
echo "Done."

npx lint-staged

npm test